sudo: required
language: node_js
script: 'true'

before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

services:
  - docker

script:
  - docker buildx build --platform linux/arm/v7 -t knajjars/rumi-server-arm .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push knajjars/rumi-server-arm