sudo: required
language: node_js
script: 'true'

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - docker

script:
  - docker buildx build --platform linux/arm/v7 -t knajjars/rumi-server-arm .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push knajjars/rumi-server-arm