sudo: required
language: node_js
script: 'true'

services:
  - docker

script:
  - docker build -t knajjars/aprta-server .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push knajjars/aprta-server
