version: '3'

services:
  aprta-server:
    container_name: aprta-server
    restart: always
    build: .
    environment:
      - PORT=4000
    ports:
      - '4000:4000'
    depends_on:
      - 'mongo'
    links:
      - 'mongo'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
